Repository entando/entando-de-app, pull requests merged in 2020-07, with the labels that each got.

#23 ENG-529 using the latest base images
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, size/XS

#24 ENG-571 new dependency structure
  pom.xml
Labels: approved, size/L

#26 ENG-773 seo plugin servlet mapping added
  src/main/webapp/WEB-INF/web.xml
Labels: approved, size/XS

#27 ENG-827 finalze pipelines
  pom.xml
Labels: approved, size/L

#28 ENG-811 update pom xml for new version of admin console
  pom.xml
Labels: size/XS

#29 ENG-781 jpmail plugin added
  pom.xml
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/sysconfig.sql
Labels: approved, size/M

#30 ENG-777: jpcontentscheduler plugin added
  pom.xml
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/sysconfig.sql
Labels: approved, size/M

#31 ENG-682 Updating entando engine version
  pom.xml
Labels: size/XS

#32 ENG-787: appbuilder integration parameters added
  pom.xml
  src/main/conf/systemParams.properties
Labels: approved, size/XS

#33 ENG-770 upgrade AC version
  pom.xml
Labels: size/XS

#34 ENG-875 Renaming CMS widgets
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/widgetcatalog.sql
Labels: size/XS

#35 ENG-875 Updating CMS version to fix ENG-875 and ENG-715
  pom.xml
Labels: size/XS

#36 ENG-771 bump up admin console version
  pom.xml
Labels: size/XS

#38 ENG-771 temporarily added appbuilder integration vars
  Dockerfile.eap
  Dockerfile.wildfly
Labels: approved, size/XS

#39 ENG-764 Updating admin console version
  pom.xml
Labels: size/XS

#42 ENG-878 Updating entando engine version
  pom.xml
Labels: size/XS

#41 ENG-922 Update default home page
  src/main/webapp/WEB-INF/aps/jsp/models/home.jsp
Labels: size/S

#43 ENG-773 Updated engine and seo plugin versions
  pom.xml
Labels: approved, size/XS

#44 ENG-773 Update entando-engine version
  pom.xml
Labels: approved, size/XS

#45 ENG-859 updating cms version
  pom.xml
Labels: size/XS

#46 ENG-415 updated jacms plugin version in the pom
  pom.xml
Labels: approved, size/XS

#47 ENG-773-seo-plugin-version-update
  pom.xml
Labels: approved, size/XS

#48 ENG-948 version bump
  pom.xml
Labels: approved, size/XS

#50 ENG-942 Paul's ENG label fixes
  pom.xml
Labels: approved, size/XS

#51 ENG-773-update-versions
  pom.xml
Labels: approved, size/XS

#52 ENG-950 cleaned up WAR dependencies
  pom.xml
Labels: approved, size/L

#53 ENG-773-update-seo-plugin-version
  pom.xml
Labels: size/XS

#54 ENG-950 removed app-view-cms
  pom.xml
Labels: approved, size/M

#55 ENG-935 updating cms and admin console versions
  pom.xml
Labels: size/XS
