Repository entando/entando-de-app, pull requests merged in 2020-05, with the labels that each got.

#14 Update pom.xml
  pom.xml
Labels: approved, size/XS

#13 ENG-338: Update entando-keycloak-plugin version to point to SNAPSHOT
  pom.xml
Labels: approved, size/XS

#15 ENG-526 add svg to allowed files for image upload
  .gitignore
  src/main/conf/systemParams.properties
Labels: approved, size/XS

#16 ENG-297 add keycloak fragments to backup
  src/main/webapp/protected/databaseBackups/20200405163949/dumpReport.xml
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/categories.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/contentattributeroles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/contentmodels.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/contentrelations.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/contents.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/contentsearch.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/guifragment.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/localstrings.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/pagemodels.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/pages.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/pages_metadata_draft.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/pages_metadata_online.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/resourcerelations.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/resources.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/sysconfig.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/uniquekeys.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/widgetcatalog.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/widgetconfig.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/widgetconfig_draft.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/workcontentattributeroles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/workcontentrelations.sql
  src/main/webapp/protected/databaseBackups/20200405163949/portDataSource/workcontentsearch.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/actionlogcommentrecords.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/actionloglikerecords.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/actionlogrecords.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/actionlogrelations.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/api_oauth_consumers.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/api_oauth_tokens.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/apicatalog_methods.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/apicatalog_services.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authgroups.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authpermissions.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authrolepermissions.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authroles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authusergrouprole.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authuserprofileattrroles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authuserprofiles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authuserprofilesearch.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authusers.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/authusershortcuts.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/dataobjectattributeroles.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/dataobjectmodels.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/dataobjectrelations.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/dataobjects.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/dataobjectsearch.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/jpkiebpm_kieformoverride.sql
  src/main/webapp/protected/databaseBackups/20200405163949/servDataSource/jpkiebpm_widgetinfo.sql
Labels: approved, size/XL

#17 ENG-128 added support for configuring cors headers from systemParams
  pom.xml
  src/main/conf/systemParams.properties
  src/main/webapp/WEB-INF/web.xml
Labels: approved, size/M

#18 ENG-128 fix the cors config on the deployed app
  src/main/webapp/WEB-INF/web.xml
Labels: approved, size/XS

#19 ENG-128 try new path for cors
  src/main/webapp/WEB-INF/web.xml
Labels: size/XS

#20 ENG-128 removed unused cors configurations
  pom.xml
  src/main/webapp/WEB-INF/web.xml
Labels: approved, size/XS

#21 ENG-562 consolidated Dockerfiles with pom to create DB
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, do-not-merge/hold, size/S
