Repository entando/entando-de-app, pull requests merged in 2020-08, with the labels that each got.

#57 Fixed some DI issues in spring
  pom.xml
Labels: approved, size/XS

#58 ENG-995 rename widgets
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/S

#59 ENG-712: update master license file
  LICENSE
Labels: approved, size/XL

#60 Update pom.xml
  pom.xml
Labels: size/XS

#61 Udated pom.xml to include new jpseo
  pom.xml
Labels: size/XS

#62 Update jacms and jpversioning versions
  pom.xml
Labels: size/XS

#63 ENG-866 version bump for Admin Console 6.2.39
  pom.xml
Labels: size/XS

#64 ENG-1032 Upgrade admin console version
  pom.xml
Labels: size/XS

#65 ENG-912 bumped engine version with widget apis upgrades
  pom.xml
Labels: size/XS

#66 ENG-912 version bump
  pom.xml
Labels: size/XS

#67 ENG-986 version bump
  pom.xml
Labels: size/XS

#68 Eng 700 increment upload max size
  src/main/conf/systemParams.properties
Labels: approved, size/XS

#69 ENG-986 version bump
  pom.xml
Labels: size/XS
