Repository entando/entando-de-app, pull requests merged in 2020-04, with the labels that each got.

#1 Update pom.xml
  jenkins-x.yml
  pom.xml
Labels: approved, size/S

#2 ENG-361 default homepage for Entando 6.1
  src/main/webapp/WEB-INF/aps/jsp/models/home.jsp
Labels: approved, size/M

#6 Update to core 6.1.1
  pom.xml
Labels: size/XS

#10 ENG-446 security fix
  pom.xml
Labels: approved, size/S

#12 ENG-446: Modified Dockerfiles to point to latest base images
  Dockerfile.eap
  Dockerfile.wildfly
Labels: size/XS
