Repository entando/entando-de-app, pull requests merged in 2020-11, with the labels that each got.

#123 ENG-1443: Update entando-de-app core parent to match the included mo…
  pom.xml
Labels: approved, size/XS

#124 ENG-1401: Seo plugin version upgrade
  pom.xml
Labels: size/XS

#125 ENG-1276 add widget category field
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/M

#126 ENG-1452 Updating cms and engine
  pom.xml
Labels: approved, size/XS

#128 ENG-1452 Updating cms and engine
  pom.xml
Labels: approved, size/XS

#127 ENG-1436 Create 2-column content type and template
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/TCL/TCL.xml
  src/main/resources/component/defaultResources/postprocess/TCL/contentModel_10004.xml
  src/main/webapp/resources/static/css/ootb/content-templates/ct-2-col.css
Labels: size/L

#129 ENG-1449 update entando-engine version
  pom.xml
Labels: approved, size/XS

#130 ENG-1438 admin dropdown on homepage navbar
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
Labels: size/S

#131 ENG-1402 implement default contents for new install
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/BNR/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content3.xml
  src/main/resources/component/defaultResources/postprocess/NWS/image2.xml
Labels: size/L

#132 ENG-1457 Add content, page, and widget config related to About Us page
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/TCL/content1.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/L

#133 ENG-1440 fix crash on displaying news archive and latest news widgets
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/XS

#134 ENG-1459 login widget issues resolved
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.LICENSE.txt
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
Labels: size/S

#135 ENG-1402 add NWS_Search_Results widget and Banner set to not searchable
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/BNR/BNR.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10022.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/static/css/ootb/content-templates/ct-news.css
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: approved, size/L

#136 ENG-1484 Move about_us page to homepage_test and exclude other pages from menu
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/S

#137 ENG-1474 update engine version
  pom.xml
Labels: approved, size/XS

#138 ENG-1468 version bump admin console - for removing AC text header
  pom.xml
Labels: size/XS

#139 ENG-1490 UX alignment based on recent prototype
  src/main/resources/component/defaultResources/postprocess/BNR/content2.xml
  src/main/resources/component/defaultResources/postprocess/BNR/contentModel_10003.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content3.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10002.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10021.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/static/css/ootb/content-templates/ct-banner.css
  src/main/webapp/resources/static/css/ootb/content-templates/ct-news.css
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: size/M

#140 ENG-1402 modify content
  src/main/resources/component/defaultResources/postprocess/BNR/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content3.xml
  src/main/webapp/resources/static/css/ootb/content-templates/ct-banner.css
Labels: size/S

#143 ENG-1402 changed related content id in about us widget config
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/XS

#144 ENG-1402 add news page with on the fly content
  src/main/resources/component/defaultResources/postprocess/NWS/NWS.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/M

#145 ENG-1402 change ootb settings
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.ootb.js
Labels: size/M

#147 ENG-1502 version bump engine
  pom.xml
Labels: approved, size/XS

#148 Update dependencies versions
  pom.xml
Labels: size/XS

#146 ENG-1402 add link to content to news list and search results
  pom.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10021.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10022.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/XS

#142 ENG-1458 sitemap improvements + individual content pages (on-the-fly)
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/NWS/NWS.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10002.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10020.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10021.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10022.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/css/sitemap.css
  src/main/webapp/resources/static/css/ootb/content-templates/ct-news.css
Labels: approved, size/XL

#149 ENG-1402 fix link style and change nav config
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/static/css/ootb/content-templates/ct-search-results.css
Labels: approved, size/M

#150 Update jpmail version
  pom.xml
Labels: size/XS

#151 Update admin console version
  pom.xml
Labels: size/XS

#152 ENG-1506 amend content template edit link to open AppBuilder instead …
  pom.xml
Labels: approved, size/XS

#154 ENG-1503 Updating jpvserioning plugin version
  pom.xml
Labels: approved, size/XS

#155 Update pom.xml
  pom.xml
Labels: size/XS

#156 Prepare for 6.3 release
  pom.xml
Labels: size/XS

#157 ENG-1516 Change entando version to 6.3
  pom.xml
Labels: size/XS

#158 ENG-1516 Change entando.version from 6.2.0-SNAPSHOT 6.3.0-SNAPSHOT
  pom.xml
Labels: size/XS

#159 ENG-1450 removing commited images and updating cms
  pom.xml
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d3.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d3.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d3.jpg
  src/main/webapp/resources/cms/images/html_code_d0.jpg
  src/main/webapp/resources/cms/images/html_code_d1.jpg
  src/main/webapp/resources/cms/images/html_code_d2.jpg
  src/main/webapp/resources/cms/images/html_code_d3.jpg
Labels: approved, size/XS

#160 ENG-1366 using correct base images from pom
  pom.xml
Labels: approved, size/XS

#161 ENG-1546 update default page favicon
  src/main/webapp/favicon.png
Labels: size/XS

#162 ENG-1514: Improvement of friendlycode validation
  pom.xml
Labels: approved, size/XS

#163 ENG-1366 increasing engine version
  pom.xml
Labels: size/XS

#153 ENG-1512: Added extra param "csp.header.extraConfig"
  src/main/conf/systemParams.properties
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/test/config/conf/systemParams.properties
Labels: approved, size/S

#164 Release 6.3.0-pr4
  pom.xml
Labels: approved, size/S
