Repository entando/entando-de-app, pull requests merged in 2020-10, with the labels that each got.

#94 ENG-1295 Updating entando-engine and jacms version
  pom.xml
Labels: size/XS

#95 ENG-1248-update-engine
  pom.xml
Labels: approved, size/XS

#97 ENG-1338 Fixes in the token generation
  pom.xml
Labels: size/XS

#98 ENG-1159 New carbon OOTB widget entries and assets + homepage page templates updated
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.LICENSE.txt
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.ootb.js
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.ootb.js.map
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: size/XL

#93 ENG-1161 OOTB Content Templates for News and Banner Content Types
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/BNR/BNR.xml
  src/main/resources/component/defaultResources/postprocess/BNR/contentModel_10003.xml
  src/main/resources/component/defaultResources/postprocess/BNR/image1.xml
  src/main/resources/component/defaultResources/postprocess/MPC/MPC.xml
  src/main/resources/component/defaultResources/postprocess/MPC/content1.xml
  src/main/resources/component/defaultResources/postprocess/MPC/contentModel_10001.xml
  src/main/resources/component/defaultResources/postprocess/MPC/contentModel_10011.xml
  src/main/resources/component/defaultResources/postprocess/NWS/NWS.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content1.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content2.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content3.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content4.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content5.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content6.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10002.xml
  src/main/resources/component/defaultResources/postprocess/NWS/contentModel_10021.xml
  src/main/resources/component/defaultResources/postprocess/NWS/image1.xml
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_1_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_2_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_3_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_4_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_5_d3.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_d0.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_d1.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_d2.jpg
  src/main/webapp/resources/cms/images/Entando_Logo_Dark_Blue_d3.jpg
  src/main/webapp/resources/static/css/ootb/content-templates/ct-banner.css
  src/main/webapp/resources/static/css/ootb/content-templates/ct-news.css
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: approved, size/XL

#99 ENG-1348-Update-versions
  pom.xml
Labels: do-not-merge/work-in-progress, size/S

#100 ENG-1159 search form widget alignment to homepage templates
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: size/XS

#101 ENG-1161 add content template css import to page templates
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/static/css/ootb/content-templates/ct-banner.css
Labels: size/S

#102 ENG-1244 widget catalog readonlyDefaultConfig db update
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: do-not-merge/work-in-progress, size/M

#103 ENG-1332 Updating entando-engine version
  pom.xml
Labels: size/XS

#104 ENG-1349 OOTB finalization
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/BNR/content1.xml
  src/main/resources/component/defaultResources/postprocess/BNR/image1.xml
  src/main/resources/component/defaultResources/postprocess/NWS/content1.xml
  src/main/resources/component/defaultResources/postprocess/NWS/image1.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/css/sitemap.css
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/ootbc-bundle/static/css/footer.css
  src/main/webapp/resources/ootbc-bundle/static/css/main.100f8365.chunk.css
  src/main/webapp/resources/ootbc-bundle/static/css/main.1aedd73d.chunk.css
  src/main/webapp/resources/ootbc-bundle/static/css/main.3560fd3e.chunk.css
  src/main/webapp/resources/ootbc-bundle/static/css/main.5ecd60fb.chunk.css
  src/main/webapp/resources/ootbc-bundle/static/css/main.fbc3daf0.chunk.css
  src/main/webapp/resources/ootbc-bundle/static/css/ootbc.css
  src/main/webapp/resources/ootbc-bundle/static/js/2.3b049955.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/2.8887cab1.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/2.cb70ec53.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/2.ebab26f7.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/main.05ed87f7.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/main.0acb2ec5.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/main.3f90a792.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/main.580b8a09.chunk.js
  src/main/webapp/resources/ootbc-bundle/static/js/runtime-main.45dc1061.js
  src/main/webapp/resources/ootbc-bundle/static/js/runtime-main.b759d654.js
  src/main/webapp/resources/ootbc-bundle/static/js/runtime-main.e2a7a9b2.js
  src/main/webapp/resources/static/css/media-queries-insurance.css
  src/main/webapp/resources/static/css/media-queries.css
  src/main/webapp/resources/static/css/ootb/carbon-components.min.css
  src/main/webapp/resources/static/css/seed-insurance.css
  src/main/webapp/resources/static/css/seed.css
  src/main/webapp/resources/static/js/seed.js
Labels: size/XXL

#105 ENG-1244 admin console version update
  pom.xml
Labels: approved, size/XS

#106 ENG-1349 version update for OOTB finalization
  pom.xml
Labels: size/XS

#107 Eng 1351 bumped baseimages
  Dockerfile.eap
  Dockerfile.wildfly
  charts/entando-de-app/Chart.yaml
  charts/entando-de-app/values.yaml
  pom.xml
  src/main/conf/systemParams.properties
Labels: size/S

#108 update pom.xml for sprint release
  pom.xml
Labels: size/S

#109 ENG-1206: Upgrade version of entando-admin-console
  pom.xml
Labels: approved, size/XS

#111 ENG-1383 updating entando-engine version
  pom.xml
Labels: approved, size/XS

#112 ENG-1276 widget rename & version bump
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/XS

#113 ENG-978 update jacms plugin
  pom.xml
Labels: approved, size/XS

#114 ENG-1397-update-engine-version
  pom.xml
Labels: size/XS

#116 ENG-978 update versions
  pom.xml
Labels: approved, size/XS

#117 ENG-963 updating cms version
  pom.xml
Labels: approved, size/XS

#118 Eng 1329 clustering
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
  src/main/jetty/jetty-env.xml
  src/main/resources/log4j2.xml
  src/main/resources/spring/aps/managers/infinispanManager.xml
  src/main/resources/spring/aps/managers/placeholder.txt
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/cms/images/entando_at_plan_1_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_1_d3.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_plan_d3.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_work_1_d3.jpg
  src/main/webapp/resources/cms/images/entando_at_work_d0.jpg
  src/main/webapp/resources/cms/images/entando_at_work_d1.jpg
  src/main/webapp/resources/cms/images/entando_at_work_d2.jpg
  src/main/webapp/resources/cms/images/entando_at_work_d3.jpg
Labels: approved, size/L

#120 ENG-963 updating cms version
  pom.xml
Labels: approved, size/XS

#122 ENG-1363 Updating cms
  pom.xml
Labels: approved, size/XS
