Repository entando/entando-de-app, pull requests merged in 2020-09, with the labels that each got.

#70 Using BOM now
  pom.xml
Labels: size/L

#71 Revert "Using BOM "
  pom.xml
Labels: size/L

#72 In jacms reverted changes erroneously merged
  pom.xml
Labels: approved, size/XS

#73 ENG-796 Update keycloak plugin
  pom.xml
Labels: approved, size/XS

#74 ENG-530 Update cms plugin version
  pom.xml
Labels: approved, size/XS

#75 ENG-1144 Updating entando-engine version
  pom.xml
Labels: size/XS

#78 ENG-1130 Updating CMS and engine version
  pom.xml
Labels: size/XS

#79 ENG-1201 Updating CMS version
  pom.xml
Labels: size/XS

#81 ENG-1201 Updating entando engine version
  pom.xml
Labels: size/XS

#80 ENG-1163 Implement OOTB page templates in new Entando install
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/static/css/ootb/carbon-components.min.css
  src/main/webapp/resources/static/css/ootb/page-templates/index.css
Labels: size/L

#83 ENG-1237 update cms plugin version
  pom.xml
Labels: approved, size/XS

#84 ENG-1280 Updating Engine and CMS version
  pom.xml
Labels: size/XS

#85 ENG-1163 align with correct figma design
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/L

#86 ENG-703 improved support for Swagger
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, size/XS

#87 ENG-1128 update to the latest entando-engine
  pom.xml
Labels: approved, size/XS

#88 ENG-1248 Update entando-engine
  pom.xml
Labels: size/XS

#89 ENG-1204 re-add keycloak fragments
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/XS

#90 ENG-1267 Add user with profile
  pom.xml
Labels: approved, size/XS

#91 ENG-1298 Updating entando-engine
  pom.xml
Labels: size/XS

#82 ENG-1160 OOTB content types with basic content templates
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/component/defaultResources/postprocess/BNR/BNR.xml
  src/main/resources/component/defaultResources/postprocess/BNR/content1.xml
  src/main/resources/component/defaultResources/postprocess/BNR/contentModel_10003.xml
  src/main/resources/component/defaultResources/postprocess/BNR/image1.xml
  src/main/resources/component/defaultResources/postprocess/CNG/CNG.xml
  src/main/resources/component/defaultResources/postprocess/CNG/content1.xml
  src/main/resources/component/defaultResources/postprocess/CNG/content2.xml
  src/main/resources/component/defaultResources/postprocess/CNG/contentModel_10001.xml
  src/main/resources/component/defaultResources/postprocess/CNG/contentModel_10011.xml
  src/main/resources/component/defaultResources/postprocess/CNG/contentModel_10012.xml
  src/main/resources/component/defaultResources/postprocess/CNG/contentModel_10013.xml
  src/main/resources/component/defaultResources/postprocess/MPC/MPC.xml
  src/main/resources/component/defaultResources/postprocess/MPC/content1.xml
  src/main/resources/component/defaultResources/postprocess/MPC/contentModel_10001.xml
  src/main/resources/component/defaultResources/postprocess/MPC/contentModel_10011.xml
  src/main/resources/component/defaultResources/postprocess/MPC/image1.xml
Labels: do-not-merge/work-in-progress, size/XL

#92 6.2.1-Sprint10-Release increment component versions for release
  pom.xml
Labels: approved, size/S
