Repository entando/entando-de-app, pull requests merged in 2020-12, with the labels that each got.

#165 ENG-1565 language widget menu item placement issue resolved
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.ootb.js
Labels: size/S

#167 Release 6.3.0-pr5
  pom.xml
Labels: approved, do-not-merge/work-in-progress, size/S

#166 ENG-1565 using locale strings for labels on items in language widget
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: size/XS

#168 ENG-1538 using latest base images that fix permissions on /tmp after …
  Dockerfile.eap
  Dockerfile.wildfly
Labels: approved, size/XS

#169 ENG-1566 Update engine
  pom.xml
Labels: approved, size/XS

#171 ENG-1631 Updating cms version
  pom.xml
Labels: approved, size/XS

#172 REL_v6.3.0-pr6
  pom.xml
Labels: approved, size/S

#174 ENG-1605 Updating cms
  pom.xml
Labels: approved, size/XS

#175 ENG-864-update-engine
  pom.xml
Labels: approved, size/XS

#176 ENG-1578 Update engine and jacms plugin versions
  pom.xml
Labels: approved, size/XS

#173 ENG-1651: reformatting of fragment code
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/L

#177 ENG-1608 Update engine version
  pom.xml
Labels: approved, size/XS

#178 ENG-1630: updating entando-plugin-jacms version
  pom.xml
Labels: approved, size/XS

#179 ENG-1653 login button fix
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/ootb-widgets/static/css/main.ac8788ef.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css
  src/main/webapp/resources/ootb-widgets/static/css/main.ootb.chunk.css.map
  src/main/webapp/resources/ootb-widgets/static/js/2.46d1e87e.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/2.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.fb2d745b.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js
  src/main/webapp/resources/ootb-widgets/static/js/main.ootb.chunk.js.map
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.1c559bb1.js.map
  src/main/webapp/resources/ootb-widgets/static/js/runtime-main.ootb.js
Labels: approved, size/M
