Repository entando/entando-de-app, pull requests merged in 2021-03, with the labels that each got.

#202 ENG-1088 Update plugin-jpmail and engine versions
  pom.xml
Labels: size/XS

#203 ENG-1929 Updating entando-engine
  pom.xml
Labels: approved, size/XS

#204 ENG-1917 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#205 ENG-1876 reverted to Infinispan 9 and improved logging
  pom.xml
  src/main/resources/log4j.xml
  src/main/resources/log4j2.xml
Labels: approved, size/M

#207 ENG-1915 Updating entando-engine-version
  pom.xml
Labels: approved, size/XS

#208 ENG-1912 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#209 Fix docker command
  README.md
Labels: approved, size/XS

#210 #ENG-2052 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#211 #ENG-2066 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#212 #ENG-2067 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#213 #ENG-276 using latest base images with correct Oracle drivers
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, size/XS

#215 #ENG-2033 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#216 ENG-2106: Integration of new Redis Plugin
  pom.xml
  src/main/resources/spring/aps/managers/infinispanManager.xml
  src/main/resources/spring/aps/placeholder.txt
  src/main/webapp/WEB-INF/web.xml
Labels: approved, size/L

#217 ENG-2099 disabled superfluous infinispan config
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, size/XS

#214 ENG-2068 update base images
  Dockerfile.eap
Labels: size/XS

#218 #ENG-2113 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#219 Update OWNERS
  OWNERS
Labels: approved, size/XS
