Repository entando/entando-de-app, pull requests merged in 2021-04, with the labels that each got.

#220 #ENG-2112 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#221 #ENG-2145 Updating cms version
  pom.xml
Labels: approved, size/XS

#222 #ENG-2183 Updating cms version
  pom.xml
Labels: approved, size/XS

#223 ENG-2259 Fix the app-engine vulnerable dependencies (ppom 6.3.9)
  pom.xml
Labels: approved, size/S

#224 ENG-2236 Updating entando engine version
  pom.xml
Labels: approved, size/XS

#225 ENG-2251 update engine and jacms versions
  pom.xml
Labels: approved, size/XS

#226 ENG-2029: Migrate the AppEngine logging to logback
  pom.xml
Labels: size/S
