Repository entando/entando-de-app, pull requests merged in 2021-12, with the labels that each got.

#280 ENG-2988 Fix engine version
  pom.xml
Labels: size/XS, approved

#282 ENG-2764: Update SEO plugin version.
  pom.xml
Labels: size/XS, approved

#283 ENG-2633 Updated engine version
  pom.xml
Labels: size/XS, approved

#284 ENG-2697 pipeline install
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  Dockerfile.eap
  Dockerfile.wildfly
  OWNERS
  OWNERS_ALIASES
  README.md
  jenkins-x.yml
  pom.xml
  skaffold.yaml
  watch.sh
Labels: size/XL

#298 ENG-3071: Installed pipelines v1.1.2 and customized to trigger develop-webui
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
  src/main/jetty/jetty-env.xml
Labels: WebUI
