Repository entando/entando-de-app, pull requests merged in 2021-07, with the labels that each got.

#241 ENG-2312: Added new parameter ("baseUrlMode") into URLTag
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
Labels: approved, size/S

#242 ENG-2148: Upgrade engine and redis plugin versions
  pom.xml
Labels: approved, size/XS

#243 ENG-2400 Updating plugin versions
  pom.xml
Labels: approved, size/S

#244 ENG-2178 Updating entando-cms and entando-engine versions to fix swagger
  pom.xml
Labels: approved, size/XS

#245 ENG-2342 Updating CMS version
  pom.xml
Labels: size/XS

#246 ENG-2178 Fixing swagger UI url
  pom.xml
Labels: approved, size/XS

#248 ENG-2552: Remove Argon2 Dependency
  pom.xml
  src/main/conf/security.properties
Labels: approved, size/S
