Repository entando/entando-de-app, pull requests merged in 2021-11, with the labels that each got.

#266 ENG-2660 update engine version
  pom.xml
Labels: size/XS

#267 ENG-2578: Update CMS version
  pom.xml
Labels: approved, size/S

#269 ENG-2578 - Updating CMS version
  pom.xml
Labels: size/XS, approved

#270 ENG-2763 update jpseo version
  pom.xml
Labels: size/XS

#271 ENG-2814: Update entando-engine version
  pom.xml
Labels: size/XS, approved

#272 ENG-2188: Liquibase integration
  pom.xml
  src/main/conf/systemParams.properties
  src/main/resources/component/defaultResources/component.xml
  src/main/resources/liquibase/defaultResources/changeSetPort.xml
  src/main/resources/liquibase/defaultResources/port/00000000000001_dataPort_production.sql
  src/main/resources/log4j.xml
  src/main/resources/sql/defaultResources/serv_data_production.sql
  src/main/webapp/WEB-INF/aps/jsp/oauth/authorize.jsp
  src/test/resources/sql/defaultResources/port_data_test.sql
  src/test/resources/sql/defaultResources/serv_data_test.sql
Labels: approved, size/XL

#274 ENG-2633 Update to latest Docker base images
  Dockerfile.eap
  Dockerfile.wildfly
Labels: size/XS, approved

#275 ENG-2633: Engine version upgrade
  pom.xml
Labels: size/XS

#276 ENG-2681: Update entando-engine version
  pom.xml
Labels: size/XS, approved

#278 ENG-2681: Fix OOTB widgets codes
  src/main/resources/liquibase/defaultResources/port/00000000000001_dataPort_production.sql
Labels: size/M, approved

#277 ENG-2633 Default migration strategy to auto
  pom.xml
  src/main/conf/systemParams.properties
Labels: size/XS

#279 ENG-2633 Update to version 7
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: size/XS
