Repository entando/entando-de-app, pull requests merged in 2021-01, with the labels that each got.

#180 ENG-1665 - EntandoEngine Simplified healthcheck (clustering fix)
  pom.xml
Labels: approved, lgtm, size/XS

#182 ENG-1626 update engine version
  pom.xml
Labels: approved, size/XS

#181 ENG-1658: added function to enable/disable CSP
  pom.xml
  src/main/conf/systemParams.properties
Labels: approved, size/XS

#183 ENG-1082 ENG-1086 ENG-1106 admin console ver bump
  pom.xml
Labels: size/XS

#185 ENG-1096 remove content scheduler
  pom.xml
Labels: approved, size/M

#184 Eng 1700 update image meta
  Dockerfile.eap
  Dockerfile.wildfly
  jenkins-x.yml
  pom.xml
Labels: size/M
