Repository entando/entando-de-app, pull requests merged in 2021-08, with the labels that each got.

#249 ENG-2032: Upgrade of dependencies version
  pom.xml
Labels: size/S

#250 ENG-2572: Upgraded dependencies version
  pom.xml
Labels: approved, size/S

#251 ENG-2587 Updating engine and CMS version
  pom.xml
Labels: size/XS, approved

#252 ENG-2436 Updating CMS version
  pom.xml
Labels: size/XS, approved
