Repository entando/entando-de-app, pull requests merged in 2021-02, with the labels that each got.

#187 ENG-1745: Restructure the AppEngine Tests
  pom.xml
  src/test/java/org/entando/aps/DummyTest.java
Labels: approved, size/M

#188 Eng 1712 redhat certification
  Dockerfile.eap
  Dockerfile.wildfly
  jenkins-x.yml
  skaffold.yaml
Labels: size/M

#189 ENG-1816 Update entando-engine version
  pom.xml
Labels: approved, size/XS

#191 Update entando-engine version
  pom.xml
Labels: size/XS

#192 ENG-1788 upgrade entando-engine version
  pom.xml
Labels: approved, size/XS

#193 Update entando-engine
  pom.xml
Labels: approved, size/XS

#190 ENG-1461 add icon files and widget types db update
  pom.xml
  src/main/resources/sql/defaultResources/port_data_production.sql
  src/main/webapp/resources/static/widget-icons/ent-breadcrumb.svg
  src/main/webapp/resources/static/widget-icons/ent-content-viewer.svg
  src/main/webapp/resources/static/widget-icons/ent-entando-apis.svg
  src/main/webapp/resources/static/widget-icons/ent-form-action.svg
  src/main/webapp/resources/static/widget-icons/ent-jpseo-content-viewer.svg
  src/main/webapp/resources/static/widget-icons/ent-nws-latest.svg
  src/main/webapp/resources/static/widget-icons/ent-user-profile-edit.svg
Labels: approved, size/M

#194 ENG-1813 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#195 ENG-1461 update entando-engine
  pom.xml
Labels: approved, size/XS

#196 ENG-1510 Updating jpseo plugin version
  pom.xml
Labels: approved, size/XS

#197 Update OWNERS
  OWNERS
Labels: approved, size/XS

#198 ENG-1875 Updating jpseo plugin version
  pom.xml
Labels: approved, size/XS

#199 ENG-1829 upgraded the MySQL and PostgreSQL drivers
  Dockerfile.eap
  Dockerfile.wildfly
  pom.xml
Labels: approved, size/XS

#200 ENG-1892 Updating entando-engine version
  pom.xml
Labels: approved, size/XS

#201 ENG-1510 Updating jpseo version
  pom.xml
Labels: approved, size/XS
